stages:
  - testing

run_tests:
  stage: testing
  tags:
    - docker
  image: python:3.10-slim
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest
  allow_failure: true
